export const MM_DUPLICATE_MODULE_ID = 'MM_DUPLICATE_MODULE_ID' as const;
export const MM_MISSING_DEPENDENCY = 'MM_MISSING_DEPENDENCY' as const;
export const MM_CYCLE_DEPENDENCY = 'MM_CYCLE_DEPENDENCY' as const;

export const MM_ALREADY_STARTED = 'MM_ALREADY_STARTED' as const;
export const MM_NOT_STARTED = 'MM_NOT_STARTED' as const;

export const MM_START_FAILED = 'MM_START_FAILED' as const;
export const MM_STOP_FAILED = 'MM_STOP_FAILED' as const;

export const EVENT_PAYLOAD_NOT_SERIALIZABLE = 'EVENT_PAYLOAD_NOT_SERIALIZABLE' as const;

export const AUTH_PASSWORD_REQUEST_CANCELED = 'AUTH_PASSWORD_REQUEST_CANCELED' as const;
export const AUTH_PASSWORD_REQUEST_TIMEOUT = 'AUTH_PASSWORD_REQUEST_TIMEOUT' as const;

export const EXTREQ_REQUEST_NOT_FOUND = 'EXTREQ_REQUEST_NOT_FOUND' as const;
export const EXTREQ_REQUEST_TIMEOUT = 'EXTREQ_REQUEST_TIMEOUT' as const;
export const EXTREQ_REQUEST_CANCELED = 'EXTREQ_REQUEST_CANCELED' as const;

export const CHAIN_RPC_HTTP_ERROR = 'CHAIN_RPC_HTTP_ERROR' as const;
export const CHAIN_RPC_TIMEOUT = 'CHAIN_RPC_TIMEOUT' as const;
export const CHAIN_RPC_ABORTED = 'CHAIN_RPC_ABORTED' as const;
export const CHAIN_RPC_INVALID_RESPONSE = 'CHAIN_RPC_INVALID_RESPONSE' as const;
export const CHAIN_RPC_ERROR_RESPONSE = 'CHAIN_RPC_ERROR_RESPONSE' as const;

export const CHAIN_PROVIDER_NOT_FOUND = 'CHAIN_PROVIDER_NOT_FOUND' as const;

export const TX_INVALID_PARAMS = 'TX_INVALID_PARAMS' as const;
export const TX_SIGN_UNSUPPORTED_NETWORK = 'TX_SIGN_UNSUPPORTED_NETWORK' as const;
export const TX_SIGN_ADDRESS_MISMATCH = 'TX_SIGN_ADDRESS_MISMATCH' as const;
export const TX_SIGN_MESSAGE_FAILED = 'TX_SIGN_MESSAGE_FAILED' as const;
export const TX_SIGN_TYPED_DATA_FAILED = 'TX_SIGN_TYPED_DATA_FAILED' as const;

export const TX_BUILD_FAILED = 'TX_BUILD_FAILED' as const;
export const TX_ESTIMATE_FAILED = 'TX_ESTIMATE_FAILED' as const;
export const TX_SIGN_TRANSACTION_FAILED = 'TX_SIGN_TRANSACTION_FAILED' as const;
export const TX_BROADCAST_FAILED = 'TX_BROADCAST_FAILED' as const;
export const TX_SAVE_FAILED = 'TX_SAVE_FAILED' as const;

export type ModuleManagerErrorCode =
  | typeof MM_DUPLICATE_MODULE_ID
  | typeof MM_MISSING_DEPENDENCY
  | typeof MM_CYCLE_DEPENDENCY
  | typeof MM_ALREADY_STARTED
  | typeof MM_NOT_STARTED
  | typeof MM_START_FAILED
  | typeof MM_STOP_FAILED;

export const WC_CONFIG_INVALID = 'WC_CONFIG_INVALID' as const;

export const WC_UNSUPPORTED_NAMESPACE = 'WC_UNSUPPORTED_NAMESPACE' as const;
export const WC_UNSUPPORTED_CHAINS = 'WC_UNSUPPORTED_CHAINS' as const;
export const WC_UNSUPPORTED_NETWORK = 'WC_UNSUPPORTED_NETWORK' as const;
export const WC_APPROVE_SESSION_FAILED = 'WC_APPROVE_SESSION_FAILED' as const;
export const WC_REJECT_SESSION_FAILED = 'WC_REJECT_SESSION_FAILED' as const;

export const NFT_SYNC_FETCHER_NOT_CONFIGURED = 'NFT_SYNC_FETCHER_NOT_CONFIGURED' as const;
export const NFT_SYNC_FETCH_FAILED = 'NFT_SYNC_FETCH_FAILED' as const;

export type EventErrorCode = typeof EVENT_PAYLOAD_NOT_SERIALIZABLE;

export type ChainErrorCode = typeof CHAIN_PROVIDER_NOT_FOUND;

export type ChainRpcErrorCode =
  | typeof CHAIN_RPC_HTTP_ERROR
  | typeof CHAIN_RPC_TIMEOUT
  | typeof CHAIN_RPC_ABORTED
  | typeof CHAIN_RPC_INVALID_RESPONSE
  | typeof CHAIN_RPC_ERROR_RESPONSE;

export type TransactionErrorCode =
  | typeof TX_INVALID_PARAMS
  | typeof TX_SIGN_UNSUPPORTED_NETWORK
  | typeof TX_SIGN_ADDRESS_MISMATCH
  | typeof TX_SIGN_MESSAGE_FAILED
  | typeof TX_SIGN_TYPED_DATA_FAILED
  | typeof TX_BUILD_FAILED
  | typeof TX_ESTIMATE_FAILED
  | typeof TX_SIGN_TRANSACTION_FAILED
  | typeof TX_BROADCAST_FAILED
  | typeof TX_SAVE_FAILED;

export type WalletConnectErrorCode =
  | typeof WC_CONFIG_INVALID
  | typeof WC_UNSUPPORTED_NAMESPACE
  | typeof WC_UNSUPPORTED_CHAINS
  | typeof WC_UNSUPPORTED_NETWORK
  | typeof WC_APPROVE_SESSION_FAILED
  | typeof WC_REJECT_SESSION_FAILED;

export type NftSyncErrorCode = typeof NFT_SYNC_FETCHER_NOT_CONFIGURED | typeof NFT_SYNC_FETCH_FAILED;
