export const MM_DUPLICATE_MODULE_ID = 'MM_DUPLICATE_MODULE_ID' as const;
export const MM_MISSING_DEPENDENCY = 'MM_MISSING_DEPENDENCY' as const;
export const MM_CYCLE_DEPENDENCY = 'MM_CYCLE_DEPENDENCY' as const;

export const MM_ALREADY_STARTED = 'MM_ALREADY_STARTED' as const;
export const MM_NOT_STARTED = 'MM_NOT_STARTED' as const;

export const MM_START_FAILED = 'MM_START_FAILED' as const;
export const MM_STOP_FAILED = 'MM_STOP_FAILED' as const;

export const EVENT_PAYLOAD_NOT_SERIALIZABLE = 'EVENT_PAYLOAD_NOT_SERIALIZABLE' as const;

export const AUTH_PASSWORD_REQUEST_CANCELED = 'AUTH_PASSWORD_REQUEST_CANCELED' as const;
export const AUTH_PASSWORD_REQUEST_TIMEOUT = 'AUTH_PASSWORD_REQUEST_TIMEOUT' as const;

export const EXTREQ_REQUEST_NOT_FOUND = 'EXTREQ_REQUEST_NOT_FOUND' as const;
export const EXTREQ_REQUEST_TIMEOUT = 'EXTREQ_REQUEST_TIMEOUT' as const;
export const EXTREQ_REQUEST_CANCELED = 'EXTREQ_REQUEST_CANCELED' as const;

export const CHAIN_RPC_HTTP_ERROR = 'CHAIN_RPC_HTTP_ERROR' as const;
export const CHAIN_RPC_TIMEOUT = 'CHAIN_RPC_TIMEOUT' as const;
export const CHAIN_RPC_ABORTED = 'CHAIN_RPC_ABORTED' as const;
export const CHAIN_RPC_INVALID_RESPONSE = 'CHAIN_RPC_INVALID_RESPONSE' as const;
export const CHAIN_RPC_ERROR_RESPONSE = 'CHAIN_RPC_ERROR_RESPONSE' as const;

export const CHAIN_PROVIDER_NOT_FOUND = 'CHAIN_PROVIDER_NOT_FOUND' as const;
export type ModuleManagerErrorCode =
  | typeof MM_DUPLICATE_MODULE_ID
  | typeof MM_MISSING_DEPENDENCY
  | typeof MM_CYCLE_DEPENDENCY
  | typeof MM_ALREADY_STARTED
  | typeof MM_NOT_STARTED
  | typeof MM_START_FAILED
  | typeof MM_STOP_FAILED;

export type EventErrorCode = typeof EVENT_PAYLOAD_NOT_SERIALIZABLE;

export type ChainErrorCode = typeof CHAIN_PROVIDER_NOT_FOUND;

export type ChainRpcErrorCode =
  | typeof CHAIN_RPC_HTTP_ERROR
  | typeof CHAIN_RPC_TIMEOUT
  | typeof CHAIN_RPC_ABORTED
  | typeof CHAIN_RPC_INVALID_RESPONSE
  | typeof CHAIN_RPC_ERROR_RESPONSE;
